### ISSUE TITLE
Add pagination to the website.

### ISSUE THREAD

**Issue by arramanila** [susmithar891/NomadNest#27]
Add pagination to the website.

Acceptance Criteria:
User Experience Impact
Make sure that by facilitating simple browsing across the information, the pagination solution improves the user experience. Users should be able to navigate between pages fast and easily, without difficulty or annoyance, thanks to a sensible pagination system. Additionally, it should be responsive, easily adjusting to various screen sizes and gadgets.

performance optimization:
Check to see if the pagination approach maximizes server resources and page loads. By retrieving and presenting just the relevant portion of data for every page, it ought to manage massive datasets well. Assess pagination's effects on other website performance indicators, like general responsiveness, server response time, and page load speed.

Estimation of time:
Frontend design and backend logic are often integrated when implementing pagination. The time estimate can change based on your website's complexity and the state of the infrastructure. 

2–3 days for backend development
1-2 days for frontend integration
Debugging and testing: 1 day

**Comment by susmithar891** [comment]
I am done with add pagination to the website
