### ISSUE TITLE
Add Oauth 2.0 to the webpagefor signing up

### ISSUE THREAD

**Issue by bhavanakum** [susmithar891/NomadNest#32]
This task involves integrating OAuth 2.0 authentication into the webpage's signup process to provide users with the option to sign up using their existing accounts from OAuth 2.0 providers such as Google, Facebook, or others. OAuth 2.0 simplifies the signup process by allowing users to authorize access to their account information without sharing their credentials directly with the website.

Acceptance Criteria:
Users should have the option to sign up using OAuth 2.0 providers, such as Google, Facebook, or other supported platforms.
Clicking on the OAuth 2.0 signup option redirects users to the respective provider's authentication page.

Estimation Time:
4-5 days

**Comment by anurag90000** [comment]
Added a page for user to see his profile stats

**Comment by bhavanakum** [comment]
webpage is created for signing up. Hence ,closing the issue.
