### ISSUE TITLE
Add user profiles to webpages

### ISSUE THREAD

**Issue by Monishareddy14** [susmithar891/NomadNest#33]

**Comment by Monishareddy14** [comment]
Acceptance Criteria: 

1. Users can register for an account using an email address and password.
2. Registered users can log in using their email and password.
3. Users should be able to edit their profile information.
4. Changes made to the profile should be saved and reflected across the platform.

Estimated Time: 4 - 5 days
The task is estimated to be high effort

**Comment by susmithar891** [comment]
Done with Add user profiles to webpages
