### ISSUE TITLE
Create database schemes for the web page

### ISSUE THREAD

**Issue by Monishareddy14** [susmithar891/NomadNest#34]

**Comment by Monishareddy14** [comment]
Acceptance Criteria:

1. Users should be able to view their profile information.
2. Users should be able to edit/update their profile information.
3. Profile information should include basic details like name, email, profile picture, etc.

Estimated time: 5 days
For this task it is based on the complexity of the project and assuming integration with existing backend and frontend systems.

**Comment by susmithar891** [comment]
Done with Create database schemes for the web page
