### ISSUE TITLE
Add filter based on price

### ISSUE THREAD

**Issue by Monishareddy14** [susmithar891/NomadNest#35]

**Comment by Monishareddy14** [comment]
Acceptance Criteria:

1.  Integrate a price filter feature into the existing interface, allowing users to set minimum and/or maximum price ranges.
2. Ensure users can input precise price ranges or use predefined options like "Under $10," "$10 - $50," "Over $50," etc.
3. Implement real-time filtering functionality to dynamically update displayed items based on the price range selected by the user without requiring page reloads.

Estimated Time: 2 - 3 days
The task is to be medium effort due to depending on the complexity of the existing system, the thoroughness of testing, and any unforeseen technical challenges encountered during development.

**Comment by susmithar891** [comment]
Done with Add filter based on price
