### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by anurag90000** [susmithar891/NomadNest#36]
#27 
Acceptance Criteria
Accessibility Considerations:
Implement accessible pagination controls that are compatible with screen readers and keyboard navigation, ensuring inclusivity for users with disabilities.
Performance Optimization:
Optimize pagination functionality to minimize loading times and enhance the overall performance of the website, particularly when navigating between pages or adjusting filtering options.
Estimated time :
The complete this task the process may take upto 1 week.

**Comment by susmithar891** [comment]
Done with Add oauth 2.0 to the webpage for registration
