### ISSUE TITLE
Add filtering based on available days

### ISSUE THREAD

**Issue by anurag90000** [susmithar891/NomadNest#37]
#39 
Filtering Functionality:

Users will be able to filter hotel room bookings based on various criteria, such as date, room type, price range, and amenities.
Filter Application:

Upon selecting filtering criteria, the system should promptly apply the chosen filters to the list of available room bookings, displaying only the relevant options to the user.
Estimated time : 
To complete this task of filtering it may take up to 7-8 days.

**Comment by susmithar891** [comment]
Done with based on Filtering on available days
