### ISSUE TITLE
Add page for user to see his profile status

### ISSUE THREAD

**Issue by anurag90000** [susmithar891/NomadNest#38]
#43
Acceptance criteria : 
Input Validation:
When users attempt to change their credentials, the system will validate the new credentials to ensure they meet any required criteria (e.g., minimum password length, special character requirements).
Authentication Confirmation:
After successfully modifying their credentials, users will receive confirmation that the changes have been applied.
Estimated Time : 
To complete this task of input validation and modifying the user credentials it takes around 2 weeks.

**Comment by susmithar891** [comment]
Done with Add page for user to see his profile status
