### ISSUE TITLE
add Filtering based on Available days

### ISSUE THREAD

**Issue by anurag90000** [susmithar891/NomadNest#39]
#44
Acceptance criteria:
Booking Functionality:

Upon clicking "Book," the system should initiate the booking process for a room.
It should generate a unique Booking ID for each booking transaction.
Storage of Bookings:
The system must store the details of each booking made, including Booking ID, room details, and customer information.
 Estimated Time : 
To complete this task it would take around 7-8 days.

**Comment by susmithar891** [comment]
Done with add Filtering based on Available days
