### ISSUE TITLE
Booking of Rooms: As User I want to search for the available rooms within the provided hotels and want to book them based on my desired dates and preferences. So that this feature smoothens up the booking process, providing me with a straightforward method to secure my accommodations.

### ISSUE THREAD

**Issue by arramanila** [susmithar891/NomadNest#4]
Estimation of efforts: Larger

Acceptance criteria:
• User can select dates and rooms of choice.
• Successful booking based on availability.
• Booking information is updated in real-time.

**Comment by susmithar891** [comment]
I am done with Booking of rooms User story Hence closing the issue
