### ISSUE TITLE
Connect digi locker to verify the user

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#54]
Estimation of Efforts: (5 to 6 days)

Considering the complexity of integrating with Digi Locker and the potential need for authentication and authorization mechanisms, I would estimate this task to take around 5-7 days.

Acceptance Criteria:

- Users should be able to initiate the verification process through Digi Locker.
- Upon successful verification, the system should update the user's verification status accordingly.

**Comment by arramanila** [comment]
Verification process through Digi Locker is successfully done.
Closing issue
