### ISSUE TITLE
Upload hotel images into cloud

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#55]
Hotel photos are uploaded to cloud storage, which offers safe and easily available picture storing for a variety of purposes, including evaluations and room views.

Acceptance criteria:
Set up the cloud storage so that you may upload images.
Hotel image uploads to the cloud are error-free for users.
The platform's intended part allows access to the uploaded images.

Estimation Time: 1-2 days

Belongs to user story #9

**Comment by Mounika1809** [comment]
Successfully uploaded hotel images to cloud
