### ISSUE TITLE
Add 360 degree image for each type of room

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#56]
#9 Integrate 360-degree viewing for each type of room in the Nomad Nest project.
Acceptance Criteria:
Implement a user interface element (e.g., button or icon) to indicate the availability of a 360-degree view for each room type.
When the user interacts with the 360-degree view button/icon, display the corresponding 360-degree image in a viewer.
Time Estimation:
5-7 days

**Comment by bhavanakum** [comment]
360 deg room  feature is added to the application . Hence closing the issue
