### ISSUE TITLE
Add UI to show 360 degree image

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#57]

**Comment by Monishareddy14** [comment]
Acceptance Criteria:
1. Identify where in the UI the 360-degree image viewer will be placed (e.g., product details page, gallery section).
2. Design the UI for the 360-degree image viewer component, including controls for rotating the image and navigation buttons (if needed).
3.  Implement functionality to load and display the 360-degree image in the viewer component.
4. Enable users to interactively rotate the image using mouse drag or touch gestures on mobile devices.
5. Thoroughly test the functionality of the 360-degree image viewer across different browsers and devices to ensure compatibility and responsiveness.

Estimated Time:4 - 5 days

**Comment by susmithar891** [comment]
Done with Add UI to show 360 degree image
