### ISSUE TITLE
Reviews and comments: As a User I want to share my hotel experience through feedback and reviews, offering insights for future guests and hotel management, so that it will strengthen community engagement and transparency.

### ISSUE THREAD

**Issue by arramanila** [susmithar891/NomadNest#6]
Estimation of efforts: High

Acceptance criteria:
• Users can view and provide reviews/comments for hotels and rooms.
• Reviews provide valuable information about the hotel's maintenance, amenities,
etc.

**Comment by susmithar891** [comment]
Done with Reviews and comments: As a User I want to share my hotel experience through feedback and reviews, offering insights for future guests and hotel management, so that it will strengthen community engagement and transparency.
