### ISSUE TITLE
Add Oauth 2.0 to the webpage for signing up

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#60]
Estimation of Efforts: 5 days

Acceptance Criteria:

Users should have the option to sign up using OAuth 2.0 providers (e.g., Google, Facebook, etc.).
Upon successful OAuth authentication, the user's basic information should be captured and stored in the application's database for user management.

**Comment by arramanila** [comment]
Successful OAuth authentication is done.
