### ISSUE TITLE
Add Ui to change password when you forgot password

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#63]

**Comment by anurag90000** [comment]
Acceptance Criteria: 
1. There should be a "Forgot Password?" link/button on the login page. 
2. Clicking on the "Forgot Password?" link/button should navigate the user to a page where they can input their email address.
3. Upon entering the email address, the system should verify its existence in the database.
4. The password reset link sent via email should lead to a page where the user can input a new password.

Estimated Time: 5 days

**Comment by susmithar891** [comment]
Closed with Add Ui to change password when you forgot password
