### ISSUE TITLE
Add functionality to change password even when user forgot the password

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#64]

**Comment by Monishareddy14** [comment]
Acceptance Criteria: 
1. Provide a field on the "Forgot Password" page where users can enter their email address.
2. Upon validation, generate a unique token and associate it with the user's account in the database. This token will be used for password reset verification.
3.  Create a "Reset Password" page accessible via the link provided in the email.
4. Provide confirmation to the user once the password has been successfully updated.
5. Implement necessary security measures, such as token expiration and one-time use, to prevent misuse of the reset functionality.

Estimated Time: 3 - 4 days

**Comment by susmithar891** [comment]
Done with add functionality to change password even when user forgot the password #64
