### ISSUE TITLE
Create dockerfile

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#68]
Dockerfile has been created successfully and this confirms that you have a reliable Dockerfile that creates a portable and reproducible environment for your application, facilitating easy deployment and scalability.

Acceptance criteria:
Make that there are no build-time failures and that the Dockerfile builds successfully with all necessary dependencies installed.
Assign the entrypoint/command, configure environment variables, expose relevant ports, set the right working directory, and copy the program files.
Verify that the application launches properly from the created Docker image, allowing features like user registration, hotel filtering, and booking.

Estimation Time: 1 day

Belongs to user stories #1 #2 #3 #4 #5 #6 #7 #8 #9

In order to ensure that important features like user authentication, hotel filtering, room booking, and others work as intended across various setups, creating a Dockerfile indirectly relates to all user stories. This is because it offers a consistent, reproducible environment for developing, testing, and deploying the application.

**Comment by Mounika1809** [comment]
Successfully created Dockerfile
