### ISSUE TITLE
Add github actions to deploy the docker image into docker hub

### ISSUE THREAD

**Issue by susmithar891** [susmithar891/NomadNest#69]

**Comment by Monishareddy14** [comment]
Acceptance Criteria:
1. Set up the workflow to trigger on every push to the main branch.
2. Configure the workflow to build the Docker image for the Nomad Nest project using a Docker file located in the project repository.
3. Authenticate with Docker Hub using Docker Hub credentials stored as secrets in GitHub repository settings.
4. Add a step to send a notification (email, Slack message, etc.) upon successful or failed deployment.

Estimated Time: 2 - 3 days
