### ISSUE TITLE
Added backend functionality to add rating and comments to the hotel and display them in UI

### ISSUE THREAD

**Issue by anurag90000** [susmithar891/NomadNest#79]

**Comment by anurag90000** [comment]
Acceptance Criteria:
1. Users can submit a numerical rating (e.g., 1 to 5 stars) for a hotel.
2. Users can submit text comments for a hotel
3. Ratings for each hotel should be displayed visually (e.g., stars, numerical average).

Estimated Time: 5-6 days

**Comment by susmithar891** [comment]
Done with Added backend functionality to add rating and comments to the hotel and display them in UI
