### ISSUE TITLE
Document Verification: As a User, I want to have the choice to digitally verify my identification documents online, ensuring a secure and efficient process for confirming my identity. So that it enhances security measures while facilitating a seamless user experience.

### ISSUE THREAD

**Issue by arramanila** [susmithar891/NomadNest#8]
Estimation of efforts: 9 days

Acceptance criteria:
• Users can digitally provide their ID for verification.
• Verification process ensures reliability and authenticity of bookings.
• Elimination of fake proofs and bookings with wrong identities.

**Comment by Mounika1809** [comment]
We have successfully done with this user story to digitally verify identification documents.
